import { useState, FormEvent } from 'react';
import { motion, AnimatePresence } from 'motion/react';
import { Search, Loader2, Sparkles, AlertCircle, Briefcase, ChevronRight, X } from 'lucide-react';
import { generateInterviewQuestions, InterviewQuestion } from './services/aiService';

export default function App() {
  const [jobTitle, setJobTitle] = useState('');
  const [questions, setQuestions] = useState<InterviewQuestion[]>([]);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [isModalOpen, setIsModalOpen] = useState(false);

  const handleSubmit = async (e: FormEvent) => {
    e.preventDefault();
    if (!jobTitle.trim()) return;

    setLoading(true);
    setError(null);
    setQuestions([]);

    try {
      const results = await generateInterviewQuestions(jobTitle);
      setQuestions(results);
      setIsModalOpen(true);
    } catch (err) {
      setError(err instanceof Error ? err.message : 'An unexpected error occurred');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="min-h-screen py-12 px-4 sm:px-6 lg:px-8 max-w-4xl mx-auto">
      {/* SEO Friendly Header */}
      <header className="text-center mb-12">
        <motion.div
          initial={{ opacity: 0, y: -20 }}
          animate={{ opacity: 1, y: 0 }}
          className="inline-flex items-center justify-center p-2 bg-blue-50 text-blue-600 rounded-full mb-4"
        >
          <Sparkles className="w-5 h-5 mr-2" />
          <span className="text-sm font-semibold uppercase tracking-wider">AI Powered Preparation</span>
        </motion.div>
        <h1 className="text-4xl sm:text-5xl font-bold text-slate-900 mb-4 tracking-tight">
          Interviewer AI
        </h1>
        <p className="text-lg text-slate-600 max-w-2xl mx-auto">
          Prepare for your next career move with personalized, high-quality interview questions generated by advanced AI.
        </p>
      </header>

      <main>
        {/* Search Section */}
        <section className="material-paper p-6 sm:p-8 mb-8" id="search-section">
          <form onSubmit={handleSubmit} className="flex flex-col sm:flex-row gap-4">
            <div className="flex-1 relative">
              <Briefcase className="absolute left-4 top-1/2 -translate-y-1/2 text-slate-400 w-5 h-5" />
              <input
                type="text"
                placeholder="e.g. Customer Success Manager"
                className="material-input pl-12"
                value={jobTitle}
                onChange={(e) => setJobTitle(e.target.value)}
                disabled={loading}
                id="job-title-input"
                aria-label="Job title"
              />
            </div>
            <button
              type="submit"
              className="material-button sm:w-auto w-full"
              disabled={loading || !jobTitle.trim()}
              id="generate-button"
            >
              {loading ? (
                <>
                  <Loader2 className="w-5 h-5 animate-spin" />
                  Generating...
                </>
              ) : (
                <>
                  Generate Questions
                  <Search className="w-5 h-5" />
                </>
              )}
            </button>
          </form>
          <p className="mt-4 text-sm text-slate-400">
            Suggested: <button onClick={() => setJobTitle('Customer Success Manager')} className="text-blue-500 hover:underline">Customer Success Manager</button>, 
            <button onClick={() => setJobTitle('Senior Software Engineer')} className="text-blue-500 hover:underline mx-1">Software Engineer</button>
          </p>
        </section>

        {/* Full Screen Modal */}
        <AnimatePresence>
          {isModalOpen && questions.length > 0 && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="fixed inset-0 z-50 flex items-center justify-center p-4 sm:p-6 bg-slate-900/60 backdrop-blur-sm"
              id="fullscreen-modal"
              onClick={() => setIsModalOpen(false)}
            >
              <motion.div
                initial={{ scale: 0.9, opacity: 0, y: 20 }}
                animate={{ scale: 1, opacity: 1, y: 0 }}
                exit={{ scale: 0.9, opacity: 0, y: 20 }}
                className="bg-white w-full max-w-5xl max-h-[90vh] overflow-hidden flex flex-col rounded-2xl shadow-2xl"
                onClick={(e) => e.stopPropagation()}
              >
                {/* Modal Header */}
                <div className="bg-slate-50 px-6 py-4 border-b border-slate-100 flex items-center justify-between sticky top-0 z-10">
                  <div>
                    <h2 className="font-semibold text-slate-700 flex items-center gap-2">
                      <Sparkles className="w-4 h-4 text-blue-500" />
                      Generated Questions for {jobTitle}
                    </h2>
                    <p className="text-xs text-slate-400 mt-0.5">3 AI Results Generated</p>
                  </div>
                  <button
                    onClick={() => setIsModalOpen(false)}
                    className="p-2 hover:bg-slate-200 rounded-full transition-colors text-slate-500"
                    aria-label="Close modal"
                  >
                    <X className="w-5 h-5" />
                  </button>
                </div>

                {/* Modal Content */}
                <div className="overflow-y-auto flex-1 divide-y divide-slate-100">
                  {questions.map((q, idx) => (
                    <motion.div
                      key={idx}
                      initial={{ opacity: 0, x: -10 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: idx * 0.1 }}
                      className="question-card p-8 sm:p-10"
                    >
                      <div className="flex gap-6 sm:gap-8">
                        <div className="flex-shrink-0 w-10 h-10 rounded-full bg-blue-100 text-blue-600 flex items-center justify-center font-bold text-lg shadow-sm">
                          {idx + 1}
                        </div>
                        <div className="flex-1">
                          <h3 className="text-2xl font-bold text-slate-900 mb-4 leading-snug">
                            {q.question}
                          </h3>
                          <div className="flex gap-4 bg-slate-50 p-5 rounded-xl border border-slate-100">
                            <div className="text-blue-500 flex-shrink-0 py-1">
                              <ChevronRight className="w-5 h-5" />
                            </div>
                            <div>
                              <span className="block text-xs font-bold uppercase tracking-widest text-slate-400 mb-2">Expert Rationale</span>
                              <p className="text-slate-600 text-base leading-relaxed">
                                {q.rationale}
                              </p>
                            </div>
                          </div>
                        </div>
                      </div>
                    </motion.div>
                  ))}
                </div>

                {/* Modal Footer */}
                <div className="p-4 border-t border-slate-100 bg-slate-50 text-center">
                  <button 
                    onClick={() => setIsModalOpen(false)}
                    className="text-sm font-medium text-blue-600 hover:text-blue-700 underline underline-offset-4"
                  >
                    Back to preparation
                  </button>
                </div>
              </motion.div>
            </motion.div>
          )}
        </AnimatePresence>

        {/* Results Section (Inline results removed as they are now in modal) */}
        <AnimatePresence mode="wait">
          {loading && (
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              exit={{ opacity: 0 }}
              className="space-y-4"
              id="loading-skeleton"
            >
              {[1, 2, 3].map((i) => (
                <div key={i} className="material-paper h-40 shimmer" />
              ))}
            </motion.div>
          )}

          {error && (
            <motion.div
              initial={{ opacity: 0, scale: 0.95 }}
              animate={{ opacity: 1, scale: 1 }}
              className="material-paper p-6 flex items-center gap-4 text-red-600 bg-red-50 border-red-100"
              id="error-message"
            >
              <AlertCircle className="w-6 h-6 flex-shrink-0" />
              <p className="font-medium">{error}</p>
            </motion.div>
          )}
        </AnimatePresence>
      </main>

      <footer className="mt-12 text-center text-slate-400 text-sm">
        <p>&copy; 2026 Interviewer AI. Powered by Google Gemini.</p>
      </footer>
    </div>
  );
}
